### PR TITLE
Fixes for modulo and division by zero

### LINKED ISSUE #382: Modulo and division by zero
I am leading the effort in the eBPF Foundation to create a standard ISA specification based on https://www.kernel.org/doc/Documentation/bpf/instruction-set.rst as a starting point.  https://github.com/dthaler/ebpf-docs/blob/update/isa/kernel.org/instruction-set.rst is the current draft in progress.

It clarifies the division-by-zero and modulo-zero requirements, where the Linux kernel currently differs from ubpf and rbpf.  The draft text currently states:

> Underflow and overflow are allowed during arithmetic operations, meaning the 64-bit or 32-bit value will wrap. If eBPF program execution would result in division by zero, the destination register SHOULD instead be set to zero, but program execution MAY be gracefully aborted instead. Similarly, if execution would result in modulo by zero, the destination register SHOULD instead be set to the source value, but program execution MAY be gracefully aborted instead.

Also, outside of eBPF I found it interesting that modulo with negative numbers currently varies by language as surveyed at per https://torstencurdt.com/tech/posts/modulo-of-negative-numbers so I also need to document that.

In PR #381 I added a number of test cases.  PREVAIL fails verification (which is ok) in most cases for things that would do modulo or division by zero but a few cases are concerning:

* 6 / [-5,5] -> [-6, 6]: this could divide by zero but PREVAIL allows it, with the result being [-6, 6].  Per the specification, this is actually ok in that x/0 should be set to 0 if the verifier passes it and if the runtime (JIT compiler or interpreter) correctly handles division by 0 as such.   It's just inconsistent with the other cases which instead fail verification.
* 6 / [-5,0] -> [-6, -1]: this one is certainly a bug.  It should either fail verification or include 0 in the range.
* 6 % [-5, 5] -> [0, 4]: this one is also a bug.  Per the specification, x%0 should be set to x if the verifier passes if and if the runtime correctly handles modulo 0 as such.  So it should either fail verification or have the range be [-5, 5].
* 6 % [7, 10] -> [0, 9]: this one is less precise than it really should be.  The result is known to be 6.

### PR DESCRIPTION
**Pull request by dthaler**
PR #381 added tests that show the current (buggy) behavior, which I recommend merging first and then rebasing this one.

This PR changes those tests and add fixes.
Since it is up to the runtime whether to support modulo/division by 0 or not (Linux does, ubpf and rbpf do not currently), I have added verifier support for those that do, when the allow_division_by_zero verifier option is set.
Modulo/division by 0 as immediate is still checked in asm_unmarshal.cpp which is bypassed by the YAML tests, but that path also uses the allow_division_by_zero verifier option.

The default is now to allow division by zero since a bunch of the ebpf-samples actually can do division by zero.  E.g. compare

`check ebpf-samples/linux/xdp_redirect_cpu_kern.o xdp_cpu_map5_lb_hash_ip_pairs`

which passes, with

`check -v --no-division-by-zero ebpf-samples/linux/xdp_redirect_cpu_kern.o xdp_cpu_map5_lb_hash_ip_pairs`

which fails with

```
...
144: Possible division by zero (r2 != 0)

0,0.872,7352
```

Fixes #382

### CODE REVIEW

File: src/assertions.cpp [hunk 1]
```diff
@@ -206,6 +206,14 @@ class AssertExtractor {
                     Assert{TypeConstraint{ins.dst, TypeGroup::ptr_or_num}}
                 };
             }
+        case Bin::Op::DIV:
+        case Bin::Op::MOD:
+            if (std::holds_alternative<Reg>(ins.v)) {
+                auto src = reg(ins.v);
+                return {Assert{TypeConstraint{ins.dst, TypeGroup::number}}, Assert{ValidDivisor{src}}};
```
Comment (elazarg) [inline src/assertions.cpp:213]: It's possible to use `allow_division_by_zero` here, which saves some computation and clutter.

**Review by elazarg — APPROVED** [review]
LGTM. I will review the YAML tests after rebasing.

File: src/assertions.cpp (hunk 1 above)
Comment (dthaler) [reply src/assertions.cpp:213]: ebpf_domain.cpp currently also checks that ValidDivisor is a number which would apply even if allow_division_by_zero is set.  Maybe there's some other code path that already does that though, I didn't add a test for that.
